### ISSUE TITLE
[Bug] Tank lacks rogue features

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/rogue#34]
I think there may have been a copy/paste error at some point. There is no rogue code in tank.c, it looks more like the xatrix or baseq2 tank.c files. Namely the blindfire and blocked stuff is missing. I first noticed this when I realized the tank wasn't doing his blindfire move which I'm used to seeing in my own rogue mod.

I guess it would be a question of starting from scratch with the original rogue tank.c, or using it as reference for restoring rogue features in the current Yamagi rogue tank.c file. With the amount of refactoring work already done, I imagine the 2nd option would take the least amount of time.

**Comment by Yamagi** [comment]
Ha! This is the second part of yquake2/yquake2#435 that I couldn't reproduce. It looks like another missmerge or bug in the crappy perl-script that I used to merge the baseq2 changes into rogue. I'll see if I can figure out what got lost and add it back.

**Comment by Yamagi** [comment]
an untested merge of the missing parts is in f7e666d. I'll test tonight. The meeting is endless and boring, but not boring enough to play Q2. ;)

**Comment by Yamagi** [comment]
It's bde5288, of course.

**Comment by BjossiAlfreds** [comment]
gcc complains about an uninitialized target vector. Looking at the code it seems the if-else that copies to the target vector (based on the blindfire local variable) is missing. rogue's code is astoundingly messy so I'm not surprised this would happen. :-)

**Comment by Yamagi** [comment]
I forced pushed a second version. Changes are:

* Add the missed if-else.
* Fix a missmerge some lines below it.
* Mention the correct commit in the commit message.

I'm still not sure if the blindfire stuff is working or not. At least tanks behave somewhat different, for example they're firing one rocket at the feed, like they should.

And there might be some behavior differences when loading an old savegame instead of starting a new game, since the entity is missing the `monsterinfo.blocked = tank_blocked` function pointer. It may be possible to hack around that by bumping the savegame version and inject the pointer into all tanks. The question is if that's really necessary.

> gcc complains about an uninitialized target vector. Looking at the code it seems the if-else that  copies to the target vector (based on the blindfire local variable) is missing. rogue's code is astoundingly messy so I'm not surprised this would happen. :-)

Messy code with a lot of commented lines in combination with a 13" laptop display. And apparently clang 8.0.1 is unable to catch such problems.

**Comment by BjossiAlfreds** [comment]
Tested the new changes. Compiles without warnings and in-game it feels right at home again, he blindfires and randomly aims at the ground like I'm used to seeing.

I wouldn't worry about the savegames. Players will simply not experience these changes until in the first unvisited level they load after updating, so at worst they will simply have the same gameplay experience as before fighting tanks (!blocked and !blindfire).

Regarding clang, a decent compiler shouldn't have any problems spotting this, could it be related to the options being passed to it?
