### ISSUE TITLE
Add Quake II RTX support

### ISSUE THREAD

**Issue by vityafx** [yquake2/rogue#74]
Thanks for supporting these old DLCs! I was trying to run the libraries with Quake II RTX but I whenever I want to save a game I get  this message: "The game doesn't support enhanced savegames", for both, rogue and xatrix. Is there any way to fix this? Is it the q2rtx what prevents save games? Can there be a workaround done for it in order to make it work? Thanks!

Having quickly glanced the code I noticed that you have rewritten a lot, along with the save game mechanism. You [said it used to use](https://github.com/yquake2/xatrix/blob/c1e438e69743f1461d45464ca769bded89c49003/src/savegame/savegame.c) function pointers previously and now it doesn't. Can we provide function pointers for compatibility with the old mechanism (if the main engine is old client, or q2rtx in this case)? I don't know the game engine, but I suppose the main engine looks for these pointers in the library and if it doesn't find them it refuses to save games. If it is so, do you think you can point to functions which I can look at so that I can try making a PR if I am able to do this myself?

**Comment by Yamagi** [comment]
This is an issue of Quake II RTX. The message comes from here: https://github.com/NVIDIA/Q2RTX/blob/master/src/server/save.c#L383

The game API of Yamagi Quake II is fully compatible with Vanilla Quake II. Old mods are working with YQ2, at least as long as they don't do any evil things. And the YQ2 game.dlls should work with Vanilla Quake 2 and any other source ports that didn't change the API. The new savegame system is in the game.dll and not in the server. It'll work with all source ports that have an unchanged game API. 

I had a short look at Q2RTX. It looks like they did some bigger changes to the way how the server and the game interacts. The functions passed from the game the server are unchanged (that's ` game_export_t`), but there're some new cvars like `g_features` that are used to communicate settings between the game and the server. Getting the YQ2 game.dll to work with Q2RTX would require to figure out what Q2RTX changed in the the server <-> game interactions and if these changes a really needed. The required changes must be implemented in our game.dlls. After that the savegame system code must be altered to match what Q2RTX expects. That are:

* https://github.com/NVIDIA/Q2RTX/blob/master/src/baseq2/g_save.c
* https://github.com/yquake2/yquake2/blob/master/src/game/savegame/savegame.c

It's likely that we can't merges such changes in our game.dlls, because supporting several game APIs would complicate the already rather fragile code a lot. It would be better to just fork the **xatrix** and **rogue** repos and maintain the changes in the forks. It shouldn't be too much hassle. Both addons are more or less done, all useful enhancements have been implemented. All that'll come are small bugfixes.
